[package]

name = "scripts"
version = "0.0.1"
authors = ["Konstantin Stepanov <me@kstep.me>"]

[lib]
name = "script-utils"

[dependencies]
url = "*"
regex = "*"
rustc-serialize = "*"

[dependencies.http]
git = "https://github.com/kstep/rust-http.git"

[dependencies.encoding]
git = "https://github.com/lifthrasiir/rust-encoding.git"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs.git"

[dependencies.xdg]
git = "https://github.com/o11c/rust-xdg.git"

[dependencies.curl]
git = "https://github.com/kstep/curl-rust.git"

[dependencies.pb]
git = "https://github.com/kstep/rust-pb.git"

[dependencies.xml-rs]
git = "https://github.com/netvl/xml-rs.git"
