[package]

name = "scripts"
version = "0.0.1"
authors = ["Konstantin Stepanov <me@kstep.me>"]

[lib]
name = "script-utils"

[dependencies]
url = "*"
regex = "*"
regex_macros = "*"
rustc-serialize = "*"
cookie = "*"
openssl = "*"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper.git"

[dependencies.encoding]
git = "https://github.com/lifthrasiir/rust-encoding.git"

[dependencies.toml]
git = "https://github.com/alexcrichton/toml-rs.git"

[dependencies.xdg]
git = "https://github.com/kstep/rust-xdg.git"

[dependencies.pb]
git = "https://github.com/kstep/rust-pb.git"

[dependencies.xml-rs]
#git = "https://github.com/netvl/xml-rs.git"
git = "https://github.com/bfops/xml-rs.git"
